### ISSUE TITLE
Title and slug not translated

### ISSUE THREAD

**Issue by foxacid** [kirby-tools/kirby-content-translator#2]
I have `2.1.11` running and both panel button and CLI work great. However, slug and title are not translated despite global whitelisting. This is my config file:

```
  'johannschopplich.content-translator' => [
    'DeepL' => [
        'apiKey' => 'xxx'
    ],
    'title' => true,
    'slug' => true
  ],
```

Any ideas?

**Comment by foxacid** [comment]
I got the titles to work via CLI using `translateTitle()` (i had been missing the 3rd argument) but not in the panel...

**Comment by johannschopplich** [comment]
Hi there!

`title` and `slug` have to be explicitly enabled on a blueprint-basis, as they don't work globally (I have to add a note in the docs):
```yml
type: content-translator
title: true
slug: true
```

Correct, for programmatic usage, you have to use the `translateTitle` method. However, there is no slug translation method as of right now. This is a todo.

**Comment by johannschopplich** [comment]
Thanks for reporting this! There was actually a bug in the code that caused global configuration overrides to never take effect. This has been fixed in the latest version. Sorry for the late response, I must have missed the notification.

Regarding the slug translation for PHP usage, I've created a separate issue #3.
